import { Link } from 'react-router-dom'

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-canvas">
      <div className="mx-auto max-w-3xl px-6 py-16 sm:px-10 lg:px-16">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm font-semibold text-ink hover:opacity-70 transition-opacity mb-10"
        >
          ← Back to Home
        </Link>

        <h1 className="font-display text-4xl font-extrabold tracking-tight text-ink mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-ink mb-10">Last Updated: June 2026</p>

        <div className="prose-ink space-y-8 text-base leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-ink mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using RevTech, you agree to be bound by these Terms of Service. If you
              do not agree to these Terms, you must discontinue use of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">2. Description of Service</h2>
            <p>
              RevTech provides a digital platform that assists users in evaluating whether electronic
              devices may be suitable for repair or recycling through questionnaire-based
              assessments, image analysis, educational resources, and related recommendations.
            </p>
            <p className="mt-3">
              Recommendations generated by the platform are informational in nature and should not be
              interpreted as professional engineering, repair, environmental, financial, or legal
              advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">3. User Responsibilities</h2>
            <p>Users agree to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Provide truthful information</li>
              <li>Upload only content they own or have permission to submit</li>
              <li>Use the platform lawfully</li>
              <li>Refrain from interfering with platform operations</li>
              <li>Avoid submitting malicious software, harmful code, or fraudulent content</li>
            </ul>
            <p className="mt-3">
              Users remain solely responsible for any content submitted through the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">
              4. Image Uploads and User Content
            </h2>
            <p>
              By submitting photographs, responses, and other content, users represent that they
              possess the necessary rights to the content, the content does not violate any law or
              third-party rights, and the content does not contain unlawful, harmful, or deceptive
              material.
            </p>
            <p className="mt-3">Users retain ownership of their submitted content.</p>
            <p className="mt-3">
              However, users grant RevTech a non-exclusive, royalty-free permission to store,
              process, analyze, reproduce, and use submitted content for providing platform services,
              research and development, system testing, machine learning model improvement, and
              platform enhancement.
            </p>
            <p className="mt-3">
              This continues until the content is deleted from the platform, except where retention
              is required for legal, security, auditing, or model training purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">
              5. Machine Learning Disclaimer
            </h2>
            <p>
              Assessment results generated by RevTech may be produced in whole or in part through
              automated systems and machine learning models. Although reasonable efforts are made to
              improve accuracy, recommendations are estimates only, may not reflect actual repair
              costs, may not identify all defects, and may contain inaccuracies.
            </p>
            <p className="mt-3">
              Users are encouraged to consult qualified technicians or authorized recycling
              facilities before taking action.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">
              6. Directory and Third-Party Services
            </h2>
            <p>
              The platform may provide information regarding repair shops, recyclers, service
              centers, or other third parties. RevTech does not guarantee quality of workmanship,
              pricing accuracy, or business practices of third parties.
            </p>
            <p className="mt-3">
              Transactions between users and third parties occur independently and at the user's own
              risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">7. Prohibited Conduct</h2>
            <p>Users may not:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Attempt unauthorized access</li>
              <li>Circumvent security measures</li>
              <li>Use automated scraping tools</li>
              <li>Upload malicious code</li>
              <li>Impersonate others</li>
              <li>Submit false information</li>
              <li>Abuse platform resources</li>
            </ul>
            <p className="mt-3">
              Violation of these Terms may result in suspension or termination of access.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">
              8. Account Suspension and Termination
            </h2>
            <p>
              We reserve the right to suspend, restrict, or terminate accounts that violate these
              Terms or threaten the integrity, security, or operation of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, RevTech shall not be liable for indirect
              damages, consequential damages, loss of data, loss of profits, business interruption,
              or decisions made based on platform recommendations.
            </p>
            <p className="mt-3">
              The platform is provided on an "as is" and "as available" basis.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">10. Indemnification</h2>
            <p>
              Users agree to defend, indemnify, and hold harmless RevTech, its developers,
              operators, affiliates, and contributors from claims, damages, liabilities, and
              expenses arising from user content, violation of these Terms, or misuse of the
              platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">
              11. Modifications to the Service
            </h2>
            <p>
              We may modify, suspend, or discontinue any portion of the platform at any time
              without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              Republic of the Philippines. Any disputes arising from these Terms shall be subject to
              the appropriate courts and authorities of the Philippines.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3">13. Contact Information</h2>
            <p>For questions regarding these Terms, contact us at support@rev.tech</p>
          </section>
        </div>
      </div>
    </div>
  )
}
