// src/lib/stationsData.ts
// Local station dataset — replace with Supabase query in production.
// Data is intentionally spread across PH regions for realistic clustering.

import { Station } from '../types/station';

export const STATIONS: Station[] = [
  // ── NCR ──────────────────────────────────────────────────────────────────
  {
    id: 'r-001',
    name: 'TechFix Manila',
    type: 'repair',
    address: '123 Rizal Ave, Santa Cruz',
    city: 'Manila',
    province: 'Metro Manila',
    lat: 14.6042,
    lng: 120.9822,
    phone: '+63 2 8123 4567',
    accepts: ['smartphones', 'laptops', 'tablets'],
    verified: true,
    rating: 4.5,
    hours: 'Mon–Sat 9AM–7PM',
  },
  {
    id: 'r-002',
    name: 'GadgetCare QC',
    type: 'repair',
    address: '45 Tomas Morato Ave',
    city: 'Quezon City',
    province: 'Metro Manila',
    lat: 14.6332,
    lng: 121.0437,
    phone: '+63 2 8234 5678',
    accepts: ['smartphones', 'laptops'],
    verified: true,
    rating: 4.2,
    hours: 'Mon–Sun 10AM–8PM',
  },
  {
    id: 'rc-001',
    name: 'EcoRecycle Hub Makati',
    type: 'recycle',
    address: '88 Ayala Ave',
    city: 'Makati',
    province: 'Metro Manila',
    lat: 14.5547,
    lng: 121.0244,
    phone: '+63 2 8345 6789',
    accepts: ['smartphones', 'laptops', 'tablets', 'batteries', 'cables'],
    verified: true,
    rating: 4.8,
    hours: 'Mon–Fri 8AM–5PM',
  },
  {
    id: 'rc-002',
    name: 'GreenTech Recycling Pasig',
    type: 'recycle',
    address: '22 Ortigas Ave',
    city: 'Pasig',
    province: 'Metro Manila',
    lat: 14.5764,
    lng: 121.0851,
    phone: '+63 2 8456 7890',
    accepts: ['all electronics'],
    verified: true,
    rating: 4.3,
    hours: 'Mon–Sat 8AM–6PM',
  },
  {
    id: 'r-003',
    name: 'iRepair Taguig',
    type: 'repair',
    address: '31 BGC High Street',
    city: 'Taguig',
    province: 'Metro Manila',
    lat: 14.5460,
    lng: 121.0509,
    phone: '+63 2 8567 8901',
    accepts: ['smartphones', 'tablets'],
    verified: true,
    rating: 4.6,
    hours: 'Mon–Sun 10AM–9PM',
  },

  // ── Cebu ─────────────────────────────────────────────────────────────────
  {
    id: 'r-004',
    name: 'CebuTech Repair Center',
    type: 'repair',
    address: '14 Colon St',
    city: 'Cebu City',
    province: 'Cebu',
    lat: 10.2969,
    lng: 123.9016,
    phone: '+63 32 234 5678',
    accepts: ['smartphones', 'laptops', 'printers'],
    verified: true,
    rating: 4.1,
    hours: 'Mon–Sat 9AM–6PM',
  },
  {
    id: 'rc-003',
    name: 'Visayas E-Waste Facility',
    type: 'recycle',
    address: '7 Osmena Blvd',
    city: 'Cebu City',
    province: 'Cebu',
    lat: 10.3116,
    lng: 123.8916,
    phone: '+63 32 345 6789',
    accepts: ['all electronics', 'batteries'],
    verified: true,
    rating: 4.4,
    hours: 'Mon–Fri 8AM–5PM',
  },
  {
    id: 'r-005',
    name: 'Mandaue Phone Clinic',
    type: 'repair',
    address: '55 A.S. Fortuna St',
    city: 'Mandaue',
    province: 'Cebu',
    lat: 10.3336,
    lng: 123.9326,
    phone: '+63 32 456 7890',
    accepts: ['smartphones'],
    verified: false,
    rating: 3.9,
    hours: 'Mon–Sat 10AM–7PM',
  },

  // ── Davao ────────────────────────────────────────────────────────────────
  {
    id: 'r-006',
    name: 'Mindanao Device Repair',
    type: 'repair',
    address: '9 JP Laurel Ave',
    city: 'Davao City',
    province: 'Davao del Sur',
    lat: 7.0731,
    lng: 125.6128,
    phone: '+63 82 234 5678',
    accepts: ['smartphones', 'laptops', 'tablets'],
    verified: true,
    rating: 4.3,
    hours: 'Mon–Sat 9AM–7PM',
  },
  {
    id: 'rc-004',
    name: 'Davao E-Waste Drop-off',
    type: 'recycle',
    address: '3 Ilustre St',
    city: 'Davao City',
    province: 'Davao del Sur',
    lat: 7.0647,
    lng: 125.6078,
    accepts: ['all electronics'],
    verified: true,
    hours: 'Mon–Fri 7AM–4PM',
  },

  // ── Iloilo ───────────────────────────────────────────────────────────────
  {
    id: 'r-007',
    name: 'Iloilo Gadget Shop',
    type: 'repair',
    address: '18 Iznart St',
    city: 'Iloilo City',
    province: 'Iloilo',
    lat: 10.6969,
    lng: 122.5644,
    phone: '+63 33 334 5678',
    accepts: ['smartphones', 'laptops'],
    verified: false,
    rating: 3.8,
    hours: 'Mon–Sat 9AM–6PM',
  },

  // ── Pampanga ─────────────────────────────────────────────────────────────
  {
    id: 'rc-005',
    name: 'Clark Green E-Recycle',
    type: 'recycle',
    address: '4 Manuel A. Roxas Hwy',
    city: 'Angeles City',
    province: 'Pampanga',
    lat: 15.1450,
    lng: 120.5887,
    phone: '+63 45 234 5678',
    accepts: ['all electronics', 'batteries', 'cables'],
    verified: true,
    rating: 4.5,
    hours: 'Mon–Fri 8AM–5PM',
  },

  // ── Cagayan de Oro ───────────────────────────────────────────────────────
  {
    id: 'r-008',
    name: 'CDO TechRepair',
    type: 'repair',
    address: '25 Corrales Ave',
    city: 'Cagayan de Oro',
    province: 'Misamis Oriental',
    lat: 8.4822,
    lng: 124.6472,
    phone: '+63 88 234 5678',
    accepts: ['smartphones', 'laptops'],
    verified: true,
    rating: 4.0,
    hours: 'Mon–Sat 9AM–6PM',
  },

  // ── Baguio ───────────────────────────────────────────────────────────────
  {
    id: 'r-009',
    name: 'Cordillera Device Clinic',
    type: 'repair',
    address: '12 Session Rd',
    city: 'Baguio City',
    province: 'Benguet',
    lat: 16.4116,
    lng: 120.5930,
    phone: '+63 74 234 5678',
    accepts: ['smartphones', 'laptops', 'tablets'],
    verified: true,
    rating: 4.2,
    hours: 'Mon–Sun 9AM–7PM',
  },
];
